import React, { useState, useMemo } from 'react';
import { formatCurrency } from '../data';
import { Search, UserPlus, Mail, Calendar, CreditCard, Filter, ArrowUpRight, CheckCircle, Plus, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface Customer {
  id: string;
  name: string;
  email: string;
  totalSpend: number;
  paymentsCount: number;
  createdDate: string;
  description?: string;
}

interface CustomersTabProps {
  transactions: any[];
  currencyCode: string;
  showToast: (msg: string) => void;
}

export default function CustomersTab({ transactions, currencyCode, showToast }: CustomersTabProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [newCustomerName, setNewCustomerName] = useState('');
  const [newCustomerEmail, setNewCustomerEmail] = useState('');
  const [newCustomerDesc, setNewCustomerDesc] = useState('');

  // Local state for dynamically added customers
  const [customCustomers, setCustomCustomers] = useState<Customer[]>(() => {
    const saved = localStorage.getItem('stripe_custom_customers');
    return saved ? JSON.parse(saved) : [];
  });

  // Calculate stats dynamically from transaction store for existing customers,
  // then merge with any custom-created customers
  const customersData = useMemo(() => {
    const map = new Map<string, { name: string; email: string; spend: number; count: number; date: string }>();

    // Seed data from transactions
    transactions.forEach(tx => {
      if (tx.customerEmail && tx.status === 'succeeded') {
        const existing = map.get(tx.customerEmail);
        if (existing) {
          existing.spend += tx.amount;
          existing.count += 1;
        } else {
          map.set(tx.customerEmail, {
            name: tx.customerName,
            email: tx.customerEmail,
            spend: tx.amount,
            count: 1,
            date: tx.date
          });
        }
      }
    });

    const list: Customer[] = [];
    map.forEach((value, email) => {
      list.push({
        id: `cus_${Math.abs(hashString(email)).toString(36).substring(0, 8).toUpperCase()}`,
        name: value.name,
        email: value.email,
        totalSpend: value.spend,
        paymentsCount: value.count,
        createdDate: value.date,
        description: 'Autogenerated client seat'
      });
    });

    // Merge custom-created customers who might not have transactions yet
    customCustomers.forEach(cust => {
      const exists = list.find(l => l.email === cust.email);
      if (!exists) {
        list.push(cust);
      } else {
        // Update values if custom created exists in actual transactions
        exists.totalSpend += cust.totalSpend;
        exists.paymentsCount += cust.paymentsCount;
      }
    });

    // Sort by spend descending
    return list.sort((a, b) => b.totalSpend - a.totalSpend);
  }, [transactions, customCustomers]);

  function hashString(str: string) {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash |= 0; // Convert to 32bit integer
    }
    return hash;
  }

  const filteredCustomers = useMemo(() => {
    return customersData.filter(c => 
      c.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.email.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [customersData, searchQuery]);

  const handleCreateCustomer = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newCustomerName.trim() || !newCustomerEmail.trim()) {
      showToast('⚠️ Please provide a valid Name and Email address.');
      return;
    }

    if (customersData.some(c => c.email.toLowerCase() === newCustomerEmail.toLowerCase())) {
      showToast('⚠️ A customer with this email address already exists!');
      return;
    }

    const newCust: Customer = {
      id: `cus_${Math.random().toString(36).substring(2, 10).toUpperCase()}`,
      name: newCustomerName,
      email: newCustomerEmail,
      totalSpend: 0,
      paymentsCount: 0,
      createdDate: new Date().toISOString(),
      description: newCustomerDesc || 'Simulated dashboard account'
    };

    const nextCustom = [newCust, ...customCustomers];
    setCustomCustomers(nextCustom);
    localStorage.setItem('stripe_custom_customers', JSON.stringify(nextCustom));

    setNewCustomerName('');
    setNewCustomerEmail('');
    setNewCustomerDesc('');
    setIsAddOpen(false);

    showToast(`👥 Customer ${newCust.name} created successfully!`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div>
          <h2 className="text-xl font-bold text-neutral-900 tracking-tight">Customers</h2>
          <p className="text-xs text-neutral-500">Manage client accounts, review contact cards, and lifetime value stats</p>
        </div>

        <button
          onClick={() => setIsAddOpen(true)}
          className="flex items-center gap-1.5 rounded-lg border border-neutral-900 bg-neutral-900 text-white px-3.5 py-1.5 text-xs font-semibold hover:bg-neutral-850 active:scale-97 transition"
        >
          <UserPlus className="h-4 w-4" />
          <span>Add Customer</span>
        </button>
      </div>

      {/* Customer search & list container */}
      <div className="rounded-xl border border-neutral-200 bg-white shadow-xs overflow-hidden">
        <div className="flex flex-col gap-4 border-b border-neutral-100 p-5 md:flex-row md:items-center md:justify-between">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-neutral-400" />
            <input
              type="text"
              placeholder="Filter by name or email address..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full rounded-lg border border-neutral-200 bg-white py-1.5 pr-3 pl-9 text-sm text-neutral-900 outline-none placeholder:text-neutral-400 focus:border-neutral-950 focus:ring-1 focus:ring-neutral-950"
            />
          </div>

          <div className="flex items-center gap-2 self-end">
            <span className="text-xs text-neutral-400 font-mono font-medium">
              COUNT: {filteredCustomers.length} client(s)
            </span>
          </div>
        </div>

        {/* Table representation */}
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-neutral-100 bg-neutral-50 text-[11px] font-semibold uppercase tracking-wider text-neutral-400">
                <th className="py-2.5 px-5">Name & Email</th>
                <th className="py-2.5 px-5">Customer ID</th>
                <th className="py-2.5 px-5">Lifetime Spending</th>
                <th className="py-2.5 px-5">Transactions</th>
                <th className="py-2.5 px-5">Created Date</th>
                <th className="py-2.5 px-5">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100 text-xs">
              {filteredCustomers.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-neutral-400">
                    No customers found matching search filter.
                  </td>
                </tr>
              ) : (
                filteredCustomers.map((cust) => (
                  <tr key={cust.id} className="hover:bg-neutral-50/50 transition duration-150">
                    <td className="py-3 px-5">
                      <div className="flex items-center gap-3">
                        <div className="flex h-7 w-7 items-center justify-center rounded-full bg-indigo-50 font-mono text-xs font-semibold text-indigo-700">
                          {cust.name.split(' ').map(n=>n[0]).join('').substring(0,2).toUpperCase()}
                        </div>
                        <div className="flex flex-col">
                          <span className="font-semibold text-neutral-900">{cust.name}</span>
                          <span className="text-[11px] text-neutral-500 leading-tight">{cust.email}</span>
                        </div>
                      </div>
                    </td>
                    <td className="py-3 px-5 font-mono text-neutral-500 font-medium">
                      {cust.id}
                    </td>
                    <td className="py-3 px-5 font-mono font-semibold text-neutral-900">
                      {formatCurrency(cust.totalSpend, currencyCode)}
                    </td>
                    <td className="py-3 px-5 font-mono text-neutral-600">
                      {cust.paymentsCount} charge(s)
                    </td>
                    <td className="py-3 px-5 text-neutral-500 font-mono">
                      {new Date(cust.createdDate).toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric',
                        timeZone: 'UTC'
                      })}
                    </td>
                    <td className="py-3 px-5 text-neutral-500 italic max-w-xs truncate" title={cust.description}>
                      {cust.description || 'No description'}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Add Customer Modal Drawer */}
      <AnimatePresence>
        {isAddOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-neutral-950/20 backdrop-blur-xs">
            {/* Modal Backdrop click to close */}
            <div className="absolute inset-0 animate-fade-in" onClick={() => setIsAddOpen(false)} />

            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="relative w-full max-w-md rounded-xl border border-neutral-200 bg-white p-6 shadow-xl z-10 space-y-4"
            >
              <div className="flex items-center justify-between border-b border-neutral-100 pb-3">
                <div className="flex items-center gap-2">
                  <UserPlus className="h-5 w-5 text-indigo-600" />
                  <h3 className="text-base font-bold text-neutral-900">Create New Customer</h3>
                </div>
                <button
                  onClick={() => setIsAddOpen(false)}
                  className="rounded-lg border border-neutral-200 p-1 text-neutral-400 hover:bg-neutral-50 hover:text-neutral-700 transition"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              <form onSubmit={handleCreateCustomer} className="space-y-4">
                <div className="space-y-1">
                  <label className="text-[11px] font-mono font-semibold text-neutral-400 uppercase">Customer Name</label>
                  <input
                    type="text"
                    required
                    placeholder="Jane Doe"
                    value={newCustomerName}
                    onChange={(e) => setNewCustomerName(e.target.value)}
                    className="w-full rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm text-neutral-900 outline-none focus:border-neutral-950 focus:ring-1 focus:ring-neutral-950"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[11px] font-mono font-semibold text-neutral-400 uppercase">Email Address</label>
                  <input
                    type="email"
                    required
                    placeholder="jane.doe@company.com"
                    value={newCustomerEmail}
                    onChange={(e) => setNewCustomerEmail(e.target.value)}
                    className="w-full rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm text-neutral-900 outline-none focus:border-neutral-950 focus:ring-1 focus:ring-neutral-950"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[11px] font-mono font-semibold text-neutral-400 uppercase">Internal Notes / Description</label>
                  <textarea
                    rows={3}
                    placeholder="Enterprise SaaS Tier customer. Billed monthly..."
                    value={newCustomerDesc}
                    onChange={(e) => setNewCustomerDesc(e.target.value)}
                    className="w-full rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm text-neutral-900 outline-none focus:border-neutral-950 focus:ring-1 focus:ring-neutral-950 resize-none"
                  />
                </div>

                <div className="flex gap-2 pt-2">
                  <button
                    type="button"
                    onClick={() => setIsAddOpen(false)}
                    className="flex-1 rounded-lg border border-neutral-200 bg-white py-2 text-center text-xs font-semibold text-neutral-700 hover:bg-neutral-50 transition"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="flex-1 rounded-lg border border-neutral-900 bg-neutral-900 py-2 text-center text-xs font-semibold text-white hover:bg-neutral-850 transition"
                  >
                    Create Customer
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
